---
#
# Ansible managed
#
repository:
  description: Install and configure vault_no_package on your system.
  homepage: https://robertdebock.nl/
  topics: vaultnopackage, ansible, molecule, tox, playbook, hacktoberfest
